#!/bin/bash
set -e

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/../package

REPO=${REPO:-niusmallnan}

for i in ${PLUGIN_NAME}/Dockerfile; do
    BASE=$(dirname $i)
    VERSION=$(cat ${BASE}/version)
    TAG=${TAG:-${VERSION}${SUFFIX}}
    IMAGE=${REPO}/rancher-${BASE}:${TAG}
    docker build -f $i -t ${IMAGE} ${BASE}
    echo ${IMAGE} > ../dist/images
    echo Built ${IMAGE}
done
